llvm: LoongArch: remove wrong pattern with fmaxa/fmina
loongson/llvm-project pull request #1
Opened 2021-12-01 14:34 UTC by xry111

maximum(fabs(-2.0), fabs(1.0)) should be 2.0.  However fmaxa gives -2.0.

2021-12-02 11:54 UTC, SixWeining commented on llvm/lib/Target/LoongArch/LoongArchInstrInfoF.td
> +def : LoongArchPat<(fminimum (fabs FGR32Opnd:$fj), (fabs FGR32Opnd:$fk)),
Thanks for the patch. But since the 'fminimum' node is not legal, it's impossible to match these pats and generate these instructions. So currently it's better to remove these until 'fminimum' was set to legal.

2021-12-03 09:43 UTC, xry111 commented on llvm/lib/Target/LoongArch/LoongArchInstrInfoF.td
> +def : LoongArchPat<(fminimum (fabs FGR32Opnd:$fj), (fabs FGR32Opnd:$fk)),
I've rebased the code onto LLVM 13 (https://github.com/xry111/llvm-project/tree/xry111/loongson-rebase/13) and tested it.  Initially I also though it's needed to set ISD::FMINIMUM/FMAXIMUM to Legal so LLVM will use the pattern, but it seems working even without an explicitly setOperationAction call.

For example:

```llvm
define float @t(float %a, float %b) nounwind {
	%call1 = tail call float @llvm.minimum.f32(float %a, float %b);
	ret float %call1;
}

define float @u(float %a, float %b) nounwind {
	%x = call float @llvm.fabs.f32(float %a);
	%y = call float @llvm.fabs.f32(float %b);
	%call1 = tail call float @llvm.minimum.f32(float %x, float %y);
	ret float %call1;
}

declare float @llvm.minimum.f32(float, float);
declare float @llvm.fabs.f32(float);
```

is compiled to:

```asm
	.text
	.section	.mdebug.abilp64,"",@progbits
	.file	"fminnum.ll"
	.text
	.globl	t                               # -- Begin function t
	.p2align	3
	.type	t,@function
t:                                      # @t
# %bb.0:
	fmin.s	$f0, $f0, $f1
	jr	$ra
.Lfunc_end0:
	.size	t, .Lfunc_end0-t
                                        # -- End function
	.globl	u                               # -- Begin function u
	.p2align	3
	.type	u,@function
u:                                      # @u
# %bb.0:
	fmina.s	$f0, $f0, $f1
	fabs.s	$f0, $f0
	jr	$ra
.Lfunc_end1:
	.size	u, .Lfunc_end1-u
                                        # -- End function
	.section	".note.GNU-stack","",@progbits
	.text
```

2021-12-04 09:35 UTC, SixWeining commented on llvm/lib/Target/LoongArch/LoongArchInstrInfoF.td
> +def : LoongArchPat<(fminimum (fabs FGR32Opnd:$fj), (fabs FGR32Opnd:$fk)),
So weird. Maybe this a bug of common code. We'll double check this.

2021-12-04 14:30 UTC, xry111 commented on llvm/lib/Target/LoongArch/LoongArchInstrInfoF.td
> +def : LoongArchPat<(fminimum (fabs FGR32Opnd:$fj), (fabs FGR32Opnd:$fk)),
Or it may be a behavior change in LLVM 13, if you can't reproduce on LLVM 11.

2021-12-06 11:44 UTC, SixWeining requested changes

2021-12-06 11:44 UTC, SixWeining commented on llvm/lib/Target/LoongArch/LoongArchInstrInfoF.td
> +def : LoongArchPat<(fminimum (fabs FGR32Opnd:$fj), (fabs FGR32Opnd:$fk)),
There is a difference between `FMINNUM` and `FMINIMUM` . 
Details:
https://llvm.org/docs/LangRef.html#llvm-minnum-intrinsic
https://llvm.org/docs/LangRef.html#llvm-minimum-intrinsic

These operations default to expand, and
1) The `llvm.minnum.* `intrinsics would be built as `FMINNUM` and expanded to a libcall of `fmin` unless we set it to legal.
2) But the `llvm.minimum.*` intrinsics would not be expanded to any libcall (See `SelectionDAGLegalize::ConvertNodeToLibcall()` ).

NaN handling:
1) `llvm.minnum`: Follows the IEEE-754 semantics for minNum, except for handling of signaling NaNs. This match’s the behavior of libm’s fmin. If either operand is a NaN, returns the other non-NaN operand. 
2) `llvm.minimum`: If either operand is a NaN, returns NaN.
3) The loongarch instruction `fmin.s` follows IEEE754-2008 `minNum(x,y)` which is the canonicalized number x if x < y, y if y < x, the canonicalized number if one operand is a number and the other a quiet NaN. Otherwise it is either x or y, canonicalized (this means results might differ among implementations). When either x or y is a signalingNaN, then the result is according to 6.2.
4) So we should not use `fmin.s` to match neither `FMINNUM` nor  `FMINIMUM`.
5) AArch64 uses `fminnm` to match `FMINNUM` and I'm not sure it is OK when the inputs contains a `SNAN`.

2021-12-06 12:45 UTC, xry111 commented
> AArch64 uses fminnm to match FMINNUM and I'm not sure it is OK when the inputs contains a SNAN.

It seems not OK: https://bugs.llvm.org/show_bug.cgi?id=27363

In LLVM 13 we have FMINNUM_IEEE and FMAXNUM_IEEE, which indicate the IEEE 754 behavior.  I'll try it on my 3A5000...

2021-12-06 15:38 UTC, xry111 commented
> llvm.minnum: Follows the IEEE-754 semantics for minNum, except for handling of signaling NaNs. This match’s the behavior of libm’s fmin. If either operand is a NaN, returns the other non-NaN operand.

By the way, libm's fmin does not act like this anymore.  TS 18661-1 says libm fmin should return qNaN for one sNaN and one normal number, just like our `fmin.d` instruction:

https://sourceware.org/git/gitweb.cgi?p=glibc.git;h=0a2546cdaa4284cc6ed6af06835fd858ba341838

2021-12-07 02:15 UTC, SixWeining approved these changes

2021-12-07 02:17 UTC, merged